# Generated by Django 3.1.4 on 2023-02-08 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('depature_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('depature_place', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
